### PR TITLE
Wrap arguments in quotes

### PR DESCRIPTION
**Pull request by knyzorg**
Fix for paths with spaces

### CODE REVIEW

**Comment by manuth** [comment]
As opposed to #61, wrapping options with `"` will break paths containing `"` (which surprisingly is allowed on Linux).
I'd recommend closing this PR in favor of PR #61 that I have created some seconds ago.

**Comment by knyzorg** [comment]
> which surprisingly is allowed on Linux

Good point. That is surprising.

**Comment by knyzorg** [comment]
Could you give this branch a try? @manuth

**Comment by manuth** [comment]
I'm about to
Sadly, these changes break the `runCommand` method.
This is the `args` variable I get:
`-noprofile -noninteractive -nologo -sta -executionpolicy unrestricted -windowstyle hidden -file e:\\Users\\Manuel\\Documents\\Projects\\VSCode-Extensions\\vscode-markdown-paste-image\\res\\win32_save_clipboard_png.ps1 c:\\Temp\\This\ is\ a\ test\\2021-12-29-21-32-06.png`

That said - escaping whitespaces using `\` doesn't work on Powershell (iirc).

On Linux, it's working fine.

**Pull request closed without merging**
